- hosts: all 
  tasks:
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest   
    - name: install git
      yum:
        name: git
        state: latest